name: Commodity Data Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 0-4' # 한국 시간 기준 월~금 오전 8시 실행

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 라이브러리 설치
        run: |
          pip install gspread google-auth google-genai yfinance requests feedparser

      - name: 파이프라인 실행
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
